AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'vagrant/**'
    - 'vendor/**/*'
    - 'bundle_bin/*'
    - 'bin/*'
    - 'chef-repo/**/*'
    - 'db/schema.rb'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Guardfile'
    - 'Gemfile'
    - 'Rakefile'


Metrics/MethodLength:
  Max: 150

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 14

Lint/DuplicatedKey:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/Lambda:
  Enabled: false

#inherit_from: .rubocop_todo.yml
