production:
  title      : Joruri
  uri        : http://joruri.example.com/
  http_proxy : <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>

test:
  title      :
  uri        :
  http_proxy :
  https_proxy:

development:
  title      :
  uri        :
  http_proxy :
  https_proxy:
