production:
  title      : Joruri
  uri        : http://joruri.example.com/
  http_proxy : 
  https_proxy: 

test:
  title      :
  uri        :
  http_proxy :
  https_proxy:

development:
  title      :
  uri        :
  http_proxy :
  https_proxy:
