production:
  transfer_to_publish: false
  transfer_opts: "-rlptvz --delete"
  transfer_opt_remote_shell: "ssh -p 22"
  transfer_dest_user:
  transfer_dest_host:
  transfer_dest_dir:

test:
  transfer_to_publish: false
  transfer_opts: "-rlptvz --delete"
  transfer_opt_remote_shell: "ssh -p 22"
  transfer_dest_user:
  transfer_dest_host:
  transfer_dest_dir:

development:
  transfer_to_publish: false
  transfer_opts: "-rlptvz --delete"
  transfer_opt_remote_shell: "ssh -p 22"
  transfer_dest_user:
  transfer_dest_host:
  transfer_dest_dir:
